# Generated by Django 4.2.7 on 2023-11-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('HORROR', 'horror'), ('THRILLER', 'thriller'), ('ROMANCE', 'romance'), ('ACTION', 'action'), ('FANTASY', 'fantasy'), ('ADVENTURE', 'adventure'), ('SUSPANCE', 'suspance'), ('BIOGRAPHY', 'biography'), ('SCIFI', 'sci-fi'), ('Anime', 'anime')], max_length=20)),
                ('release_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actors', models.ManyToManyField(to='api.actor')),
            ],
        ),
    ]
